services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    command: sh -c "npx knex migrate:latest && npm start"
  redis:
    image: redis:7
    ports:
      - "6379:6379"


  db:
    image: postgres:15
    ports:
          - "5432:5432"
    environment: 
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: password
        POSTGRES_DB: realtime_chat
    volumes:
          - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: